import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import Hero from "@/components/Hero";
import AppFooter from "@/components/AppFooter";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Jadoo Website",
	description: "Generated by Ahmed Ali",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='main-app mx-auto mt-5 lg:mt-10 max-w-[85%] mb-20'>
					<Navigation />
					<Hero />
					{children}
					{/* <AppFooter /> */}
				</div>
			</body>
		</html>
	);
}
